export const POR_NUMBER: Record<number, string> = {
  0: 'None',
  1: 'Default',
  2: 'Alphonse',
  3: 'Eleanor',
  4: 'Cybil',
  5: 'Rictor',
  6: 'Ivanna',
  7: 'Shiven',
  8: 'Orson',
  9: 'special mermaid',
  10: 'some special male character',
  11: 'some special female character',
  12: 'special angel knight',
  13: 'Glycinia',
  14: 'Lubinia',
  15: 'some sort of demon (possibly Saya)',
  16: 'special male',
  17: 'Deneb',
  18: 'older male (see what I mean about additions ...)',
  19: 'younger knight',
  20: 'female swordswoman (Ivannas former instructor)',
  21: 'female (looks like a priest or something)',
  22: 'demonic looking beast',
  23: 'demonic looking beast',
  24: 'fallen angel',
  25: 'Standard Male Soldier',
  26: 'Standard Female Soldier',
  27: 'Standard Male Ninja',
  28: 'Standard Female Ninja',
  29: 'Standard Male Archer',
  30: 'Standard Female Archer',
  31: 'Standard Male Wizard',
  32: 'Standard Female Wizard',
  33: 'Standard Male Cleric',
  34: 'Standard Female Cleric',
  35: 'Stan (the Bandit)',
  36: 'Mullin (the Wizard)',
  37: 'Enemy Female Archer',
  38: 'Enemy Male Knight (I think ...)',
  39: 'Enemy Male Ninja (or possibly Dark Stalker)',
  40: 'Enemy Beast Tamer',
  41: 'Enemy Cleric',
  42: 'Enemy Dragoon (or possibly Predator)',
  43: 'Cybil (in enemy colors, I think)',
  44: 'Lich (possibly in enemy colors, its hard to tell)',
  45: 'Angel Knight',
  46: 'some sort of demon (possibly Saya)',
  47: 'Mermaid',
  48: 'Duke Knight',
  49: 'Standard Male Soldier',
  50: 'Standard Female Soldier',
  51: 'Stan (but the palette is messed up)',
  52: 'Female Knight (but the palette is messed up)',
  53: 'Duke Knight (but the palette is messed up)',
  54: 'Unknown Female (blue version)',
  55: 'Enemy Female Ninja',
  56: 'Unknown Female (green version of 54)',
  57: 'Elric (in enemy colors)',
  58: 'Swordmaster',
  59: 'Female Priest (but in yellow ...)'
}
export const POR_URL: Record<number, string> = {
  0: 'None',
  1: 'Default',
  2: 'alphonse',
  3: 'eleanor',
  4: 'cybil',
  5: 'rictor',
  6: 'ivanna',
  7: 'shiven',
  8: 'orson',
  9: 'aerial',
  10: 'elrik',
  11: 'euphaire',
  12: 'lobelia',
  13: 'glycinia',
  14: 'lubina',
  15: 'some sort of demon (possibly Saya)',
  16: 'special male',
  17: 'deneb',
  18: 'older male (see what I mean about additions ...)',
  19: 'younger knight',
  20: 'female swordswoman (Ivannas former instructor)',
  21: 'female (looks like a priest or something)',
  22: 'demonic looking beast',
  23: 'demonic looking beast',
  24: 'fallen angel',
  25: 'Standard Male Soldier',
  26: 'Standard Female Soldier',
  27: 'Standard Male Ninja',
  28: 'Standard Female Ninja',
  29: 'Standard Male Archer',
  30: 'Standard Female Archer',
  31: 'Standard Male Wizard',
  32: 'Standard Female Wizard',
  33: 'Standard Male Cleric',
  34: 'Standard Female Cleric',
  35: 'Stan (the Bandit)',
  36: 'Mullin (the Wizard)',
  37: 'Enemy Female Archer',
  38: 'Enemy Male Knight (I think ...)',
  39: 'Enemy Male Ninja (or possibly Dark Stalker)',
  40: 'Enemy Beast Tamer',
  41: 'Enemy Cleric',
  42: 'Enemy Dragoon (or possibly Predator)',
  43: 'Cybil (in enemy colors, I think)',
  44: 'Lich (possibly in enemy colors, its hard to tell)',
  45: 'Angel Knight',
  46: 'some sort of demon (possibly Saya)',
  47: 'Mermaid',
  48: 'Duke Knight',
  49: 'Standard Male Soldier',
  50: 'Standard Female Soldier',
  51: 'Stan (but the palette is messed up)',
  52: 'Female Knight (but the palette is messed up)',
  53: 'Duke Knight (but the palette is messed up)',
  54: 'Unknown Female (blue version)',
  55: 'Enemy Female Ninja',
  56: 'Unknown Female (green version of 54)',
  57: 'Elric (in enemy colors)',
  58: 'Swordmaster',
  59: 'Female Priest (but in yellow ...)'
}
